const db_m = {
  
    "1": { name: 'one' },
     "2": { name: 'two'},
     "3": {name:'three'},
     "4":{name:'four'},
    "5":{name:'five'},
    "6":{name:'six'},
    "7":{name:'seven'},
    "8":{name:'eight'},
    "9":{name:'nine'},
    "10":{name:'ten'},
    "11":{name:'eleven'},
    "12":{name:'twelve'},
    "13":{name:'zero'},
    "14":{name:'zero'},
    "15":{name:'zero'},
    "16":{name:'zero'},
    "17":{name:'zero'},
    "18":{name:'zero'},
    "19":{name:'zero'},
    "20":{name:'zero'},
    "21":{name:'zero'},
    "22":{name:'zero'},
    "23":{name:'zero'},
    "24":{name:'zero'},
    "25":{name:'zero'},
    "26":{name:'zero'},
    "27":{name:'zero'},
    "28":{name:'zero'},
    "29":{name:'zero'},

   };
   export default db_m;